AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Cloudformation roles

Resources:
  EfsCfnStackRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: cloudformation.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonElasticFileSystemFullAccess


Outputs:
  EfsCfnStackRole:
    Value: !Ref EfsCfnStackRole