AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Security Setup for A ECS clusters

Parameters:

  AppName:
    Type: String

  DbiResourceId:
    Type: String
    #aws rds describe-db-instances --query "DBInstances[*].[DBInstanceIdentifier,DbiResourceId]" --region eu-central-1

  EfsId:
    Type: String
    Description: Default filesystem Id

Resources:

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - ecs-tasks.amazonaws.com
          Action:
            - sts:AssumeRole
      Policies:
        - PolicyName: !Ref AWS::StackName
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              -
                Effect: Allow
                Action:
                  - rds-db:connect
                Resource: !Sub arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:${DbiResourceId}/${AppName}
              -
                Action:
                - elasticfilesystem:ClientMount
                - elasticfilesystem:ClientWrite
                - elasticfilesystem:ClientRootAccess
                Effect: Allow
                Resource: !Sub arn:aws:elasticfilesystem:${AWS::Region}:${AWS::AccountId}:file-system/${EfsId}
                Condition:
                  StringEquals:
                    elasticfilesystem:AccessPointArn: !GetAtt EfsAccessPoint.Arn

  EfsAccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref EfsId
      PosixUser:
        Gid: 0
        Uid: 0
      RootDirectory:
        CreationInfo:
          OwnerGid: 0
          OwnerUid: 0
          Permissions: "0755"
        Path: !Sub /mnt/apps-efs/${AppName}



Outputs:

  TaskRole:
    Value: !Ref TaskRole
    Description: ECS task role
    Export:
      Name: !Sub "${AWS::StackName}:ecs-task-role"

  EfsAccessPoint:
    Value: !Ref EfsAccessPoint
    Description: Efs access point
    Export:
      Name: !Sub "${AWS::StackName}:efs-access-point"