AWSTemplateFormatVersion: 2010-09-09
Description: >
  ECS Cluster

Parameters:

  AttiniEnvironmentName:
    Type: String
    Description: The name of the environment the stack created belongs to
    Default: stage

  PrivateDomain:
    Type: String

Resources:
  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref AWS::StackName
      ClusterSettings:
        - Name: containerInsights
          Value: enabled

  AppMesh:
    Type: AWS::AppMesh::Mesh
    Properties:
      MeshName: !Sub ${AWS::StackName}-mesh
      Spec:
        EgressFilter:
          Type: ALLOW_ALL


  CloudMapNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Description: !Sub Cloudmap for ${AttiniEnvironmentName}
      Vpc:
        Fn::ImportValue:
          !Sub "${AttiniEnvironmentName}-vpc:id"
      Name: !Sub sd.${AttiniEnvironmentName}.${PrivateDomain}


Outputs:

  EcsClusterName:
    Value: !Ref EcsCluster

  CloudMapNamespaceId:
    Value: !Ref CloudMapNamespace

  CloudMapNamespaceName:
    Value: !Sub sd.${AttiniEnvironmentName}.${PrivateDomain}

  AppMesh:
    Value: !GetAtt AppMesh.MeshName